### ISSUE TITLE
Suggestion: temporary file creation is redundant

### ISSUE THREAD

**Issue by rfominych** [grundic/confluence-page-copier#10]
How system works now:
1. Attachment is downloaded
2. Temporary file is created
3. File is uploaded

How system should work:
1. Attachment is downloaded to memory (stream)
2. Attachment is uploaded from memory

Now there is problem with Confluence and host(script) file system file naming compatibility. For example national symbols, special symbols like BOM and other, prohibited windows filename symbols like ":" that are allowed in Confluence as filenames. If file will not be saved to the host filesystem - then all these problems will not exist

**Comment by grundic** [comment]
It would make sense if the process would take place at Confluence server, then of course putting it to the memory could be treated as optimization. In our case we always download file, so it won't make much difference putting it to the memory of file, IMO.
Also it could happen that either file is too big or memory is not enough, so the file won't fit to the memory.

What about names -- I can save file as md5 sum from it's content or generate random string and during upload rename it back. What do you think?

**Comment by grundic** [comment]
Okay, maybe I was not completely correct: at least about the file size and memory: if there is swap it should help for these cases with big files..
I changed script, so now it uses in-memory content.
Could you please have a look?

**Comment by rfominych** [comment]
error when copying attachment with simple normal name like "empty.docx"

c:\python27\python.exe copier.py --username="_" --password="_" --endpoint="https://_.atlassian.net/wiki" --src-id=74514552 --dst-parent-id=66322435 --dst-space="~rf" --src-space="~rf"
DEBUG:confl-copier:Searching page by id '74514552'
DEBUG:confl-copier:Setting ancestor id to 66322435
DEBUG:confl-copier:Searching page by space '~rf' and title 'test page 1 (2)'
DEBUG:confl-copier:Found 0 page(s)
DEBUG:confl-copier:Searching page by id '66322435'
INFO:confl-copier:Copying [~rf]:'_├ó┬Ç┬Ös Home'/'test page 1' => [~rf]:'*├ó┬Ç┬Ös Home'/'test page 1 (2)'
INFO:confl-copier:Copying 1 attachment(s)
Traceback (most recent call last):
  File "copier.py", line 469, in <module>
    recursion_limit=args.recursion_limit
  File "copier.py", line 113, in copy
    self._copy_attachments(source, page_copy_id)
  File "copier.py", line 317, in _copy_attachments
    attachment_comment = attachment['metadata']['comment']
KeyError: 'comment'

**Comment by grundic** [comment]
I was not able to reproduce this issue, but try new version, it should work fine now.
Version of Confluence I use is **5.8.16**.

**Comment by rfominych** [comment]
I am using cloud Confluence 1000.132.1, running the script on Windows 10 platform

Now attachments are working like this:
- with "normal" name copied successfully
- with "unsupported windows name" "image2016-6-22 14:40:49.png" copied successfully (before it was not working on windows)
- with national symbols "Iðnó.txt" - fails (before it was also failing)
- with BOM in the filename ")﻿.png" - fails (before it was also failing)

so for me it looks like kind of not perfect but acceptable behavior

DEBUG:confl-copier:Downloading 'I─é┬░n─é┼é.txt' attachment
DEBUG:confl-copier:Creating new attachment 'I─é┬░n─é┼é.txt'
Traceback (most recent call last):
  File "copier.py", line 471, in <module>
    recursion_limit=args.recursion_limit
  File "copier.py", line 113, in copy
    self._copy_attachments(source, page_copy_id)
  File "copier.py", line 345, in _copy_attachments
    'comment': attachment_comment
  File "c:\python27\lib\site-packages\PythonConfluenceAPI\api.py", line 820, in create_new_attachment_by_content_id
    callback=callback)
  File "c:\python27\lib\site-packages\PythonConfluenceAPI\api.py", line 140, in _service_post_request
    return self._service_request("POST", _args, *_kwargs)
  File "c:\python27\lib\site-packages\PythonConfluenceAPI\api.py", line 116, in _service_request
    response.raise_for_status()
  File "c:\python27\lib\site-packages\requests\models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://*.atlassian.net/wiki/rest/api/content/75202568/child/attachment

DEBUG:confl-copier:Downloading 'image2016-6-22 14:40:49.png' attachment
DEBUG:confl-copier:Creating new attachment 'image2016-6-22 14:40:49.png'
DEBUG:confl-copier:Downloading ')─Å┼Ñ┼╝.png' attachment
DEBUG:confl-copier:Creating new attachment ')─Å┼Ñ┼╝.png'
Traceback (most recent call last):
  File "copier.py", line 471, in <module>
    recursion_limit=args.recursion_limit
  File "copier.py", line 113, in copy
    self._copy_attachments(source, page_copy_id)
  File "copier.py", line 345, in _copy_attachments
    'comment': attachment_comment
  File "c:\python27\lib\site-packages\PythonConfluenceAPI\api.py", line 820, in create_new_attachment_by_content_id
    callback=callback)
  File "c:\python27\lib\site-packages\PythonConfluenceAPI\api.py", line 140, in _service_post_request
    return self._service_request("POST", _args, *_kwargs)
  File "c:\python27\lib\site-packages\PythonConfluenceAPI\api.py", line 116, in _service_request
    response.raise_for_status()
  File "c:\python27\lib\site-packages\requests\models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://*.atlassian.net/wiki/rest/api/content/75202569/child/attachment

**Comment by grundic** [comment]
Can you rename existing attachment to one of that failing? In the Confluence interface you can click on attachments properties and set new name there.

**Comment by grundic** [comment]
Yep, it's possible to rename file to something like `I─é┬░n─é┼é.txt`. Will take a look what could be done.

**Comment by rfominych** [comment]
I─é┬░n─é┼é.txt - is printed on the windows console. real file name is "Iðnó.txt"
')─Å┼Ñ┼╝.png' - is printed on the windows console. real file name is  ")﻿.png" (that contains BOM after closing bracket before dot)

so here are two problems actually, one that file is not copied (bigger problem), and one that file name is displayed incorrectly

**Comment by rfominych** [comment]
for small copy copy jobs one can simply go to Confluence and change attachment file names by hand

the real problem would be if one has to copy big projects full of attachments with national symbols in filenames

**Comment by grundic** [comment]
I agree.. But don't know how to do it correctly with `requests` library. I've tried encoding it with `urllib.quote(attachment_name)`, but in this case attachment renamed to something like `I%E2%94%80%C3%A9%E2%94%AC%E2%96%91n%E2%94%80%C3%A9%E2%94%BC%C3%A9.txt`
Here are some post:
http://stackoverflow.com/questions/20591599/why-arent-post-names-with-unicode-sent-correctly-when-using-multipart-form-data
http://stackoverflow.com/questions/24397418/python-requests-issues-with-non-ascii-file-names

**Comment by rfominych** [comment]
I think we can close this issue since suggestion is implemented, and functionality of the script improved by being host-platform-independent

**Comment by grundic** [comment]
It should be possible, but needs some time to implement.
http://stackoverflow.com/questions/28282318/how-to-do-multi-part-upload-with-python-requests-library-and-unicode-filename
http://linuxonly.nl/docs/68/167_Uploading_files_with_non_ASCII_filenames_using_Python_requests.html

**Comment by grundic** [comment]
@rfominych, looks like it works now: you can copy pages with attachments, containing non ASCII symbols in their names. 
Can you have a look?

**Comment by rfominych** [comment]
now files are copied, but attachment names are changed in the process, and file with national symbols in the filename becomes unaccessible from the page's link:

INFO:confl-copier:Copying 3 attachment(s)
DEBUG:confl-copier:Downloading ')─Å┼Ñ┼╝.png' attachment
DEBUG:confl-copier:Creating new attachment ')─Å┼Ñ┼╝.png'
DEBUG:confl-copier:Downloading 'I─é┬░n─é┼é.docx' attachment
DEBUG:confl-copier:Creating new attachment 'I─é┬░n─é┼é.docx'
DEBUG:confl-copier:Downloading 'image2016-6-22 14:40:49.png' attachment
DEBUG:confl-copier:Creating new attachment 'image2016-6-22 14:40:49.png'

national symbols - Iðnó.docx copied to the file IĂ°nĂł.docx:
page link: https://*.atlassian.net/wiki/pages/viewpage.action?pageId=75628552# (broken link, no attachment)

BOM: ")﻿.png" copied to the ")ďťż.png"
page link: https://*.atlassian.net/wiki/download/attachments/75628552/%29%C4%8F%C5%A5%C5%BC.png?version=1&modificationDate=1467017832058&api=v2 (accessible)

maybe changes should be reverted so that copying stops when "bad" file is encountered (so it can be renamed manually)

**Comment by rfominych** [comment]
important notice:

master branch should be reverted to the previous version that "stops on copy non-ascii filename" and gives out error, so user can manually change attachment name and then copy again

all further "playing" should be conducted in according branch

page visitors should download correct version of application, that keeps pages consistent on copy

current version copies attachments that it cannot handle properly, as a result these attachments become broken after copying - it's data loss situation and therefore the bug is critical

**Comment by rfominych** [comment]
bug is confirmed with the latest version

**Comment by grundic** [comment]
@rfominych,
Yep I totally agree. Was a little bit busy, sorry for that.
Will revert this code and move to separate branch.

**Comment by grundic** [comment]
Moved last commit to https://github.com/grundic/confluence-page-copier/tree/non_ascii_attachments

**Comment by rfominych** [comment]
weird, --dst-parent parameter not working

so page is copied to the root

C:\Users\roman\Documents\documentation\confluence-page-copier-master>c:\python27\python.exe copier.py --username="*" --password="*" --endpoint="https://*.atlassian.net/wiki" --src-id=81133576 --dst-parent-id=81133572 --dst-space="~rf" --src-space="~rf"
DEBUG:confl-copier:Searching page by id '81133576'
DEBUG:confl-copier:Setting ancestor id to 66322435
DEBUG:confl-copier:Searching page by space '~rf' and title 'good attach page (1)'
DEBUG:confl-copier:Found 0 page(s)
DEBUG:confl-copier:Searching page by id '66322435'
INFO:confl-copier:Copying [~rf]:'Roman Fominych├ó┬Ç┬Ös Home'/'good attach page' => [~rf]:'Roman Fominych├ó┬Ç┬Ös Home'/'good attach page (1)'
INFO:confl-copier:Copying 1 attachment(s)
DEBUG:confl-copier:Downloading 'BET-255.png' attachment
DEBUG:confl-copier:Creating new attachment 'BET-255.png'

**Comment by rfominych** [comment]
confirm, now application throws exception when "illegal file name" is encountered, thus file structure is correctly preserved

C:\Users\roman\Documents\documentation\confluence-page-copier-master>c:\python27\python.exe copier.py --username="_" --password="_" --endpoint="https://_.atlassian.net/wiki" --src-id=74842114 --dst-parent-id=81133572 --dst-space="~rf" --src-space="~rf"
DEBUG:confl-copier:Searching page by id '74842114'
DEBUG:confl-copier:Setting ancestor id to 66322435
DEBUG:confl-copier:Searching page by space '~rf' and title 'attachment page (1)'
DEBUG:confl-copier:Found 0 page(s)
DEBUG:confl-copier:Searching page by id '66322435'
INFO:confl-copier:Copying [~rf]:'Roman Fominych├ó┬Ç┬Ös Home'/'attachment page' => [~rf]:'Roman Fominych├ó┬Ç┬Ös Home'/'attachment page (1)'
INFO:confl-copier:Copying 3 attachment(s)
DEBUG:confl-copier:Downloading ')─Å┼Ñ┼╝.png' attachment
DEBUG:confl-copier:Creating new attachment ')─Å┼Ñ┼╝.png'
Traceback (most recent call last):
  File "copier.py", line 471, in <module>
    recursion_limit=args.recursion_limit
  File "copier.py", line 113, in copy
    self._copy_attachments(source, page_copy_id)
  File "copier.py", line 345, in _copy_attachments
    'comment': attachment_comment
  File "c:\python27\lib\site-packages\PythonConfluenceAPI\api.py", line 820, in create_new_attachment_by_content_id
    callback=callback)
  File "c:\python27\lib\site-packages\PythonConfluenceAPI\api.py", line 140, in _service_post_request
    return self._service_request("POST", *args, *_kwargs)
  File "c:\python27\lib\site-packages\PythonConfluenceAPI\api.py", line 116, in _service_request
    response.raise_for_status()
  File "c:\python27\lib\site-packages\requests\models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://*.atlassian.net/wiki/rest/api/content/81133573/child/attachment
