### ISSUE TITLE
--dst-parent parameter not working

### ISSUE THREAD

**Issue by rfominych** [grundic/confluence-page-copier#14]
so page is copied to the root

C:\Users\roman\Documents\documentation\confluence-page-copier-master>c:\python27\python.exe copier.py --username="" --password="" --endpoint="https://*.atlassian.net/wiki" --src-id=81133576 --dst-parent-id=81133572 --dst-space="~rf" --src-space="~rf"
DEBUG:confl-copier:Searching page by id '81133576'
DEBUG:confl-copier:Setting ancestor id to 66322435
DEBUG:confl-copier:Searching page by space '~rf' and title 'good attach page (1)'
DEBUG:confl-copier:Found 0 page(s)
DEBUG:confl-copier:Searching page by id '66322435'
INFO:confl-copier:Copying [~rf]:'Roman Fominych├ó┬Ç┬Ös Home'/'good attach page' => [~rf]:'Roman Fominych├ó┬Ç┬Ös Home'/'good attach page (1)'
INFO:confl-copier:Copying 1 attachment(s)
DEBUG:confl-copier:Downloading 'BET-255.png' attachment
DEBUG:confl-copier:Creating new attachment 'BET-255.png'

**Comment by gcaracuel** [comment]
+1 new page is created under Space root document

**Comment by grundic** [comment]
Hello... Sorry, have not much time though.
Try to check it later.
Thank you, guys.
