### ISSUE TITLE
Page copy w/ attachment error

### ISSUE THREAD

**Issue by andrew-boutin** [grundic/confluence-page-copier#3]
I am having an issue copying any pages that have an attachment.

The page gets copied, but then an error gets thrown when attempting to copy the attachment. It leaves an image that says _? Unknown Attachment_ in its place.

I get the same error attempting to do the copy in a personal space & regular space. Also, have tried with different attachment types. Also, tested on a page with just text and a single attachment.

> $ python2 copier.py --src-id=27183904 --dst-title-template="{title} new" --endpoint="..." --username="..." --password="..."
> DEBUG:confl-copier:Searching page by id '27183904'
> DEBUG:confl-copier:Setting destination space key to source's value '~andy_boutin'
> DEBUG:confl-copier:Setting ancestor id to 2884752
> DEBUG:confl-copier:Searching page by space '~andy_boutin' and title 'Dummy new'
> DEBUG:confl-copier:Found 0 page(s)
> INFO:confl-copier:Copying '~andy_boutin/Dummy' => '~andy_boutin/Dummy new'
> INFO:confl-copier:Copying 1 attachment(s)
> DEBUG:confl-copier:Downloading 'useravatar.png' attachment
> DEBUG:confl-copier:Removing temp directory '/tmp/tmpEMyf53'
> Traceback (most recent call last):
>   File "copier.py", line 422, in <module>
>     recursion_limit=args.recursion_limit
>   File "copier.py", line 106, in copy
>     self._copy_attachments(source, page_copy_id)
>   File "copier.py", line 292, in _copy_attachments
>     content = self._client._service_get_request(sub_uri=attachment['_links']['download'][1:], raw=True)
>   File "/usr/local/lib/python2.7/site-packages/PythonConfluenceAPI/api.py", line 131, in _service_get_request
>     return self._service_request("GET", _args, *_kwargs)
>   File "/usr/local/lib/python2.7/site-packages/PythonConfluenceAPI/api.py", line 111, in _service_request
>     uri = urljoin(self.uri_base, sub_uri)
>   File "/usr/local/lib/python2.7/site-packages/future/backports/urllib/parse.py", line 418, in urljoin
>     base, url, _coerce_result = _coerce_args(base, url)
>   File "/usr/local/lib/python2.7/site-packages/future/backports/urllib/parse.py", line 115, in _coerce_args
>     raise TypeError("Cannot mix str and non-str arguments")
> TypeError: Cannot mix str and non-str arguments

![image](https://cloud.githubusercontent.com/assets/4227775/15025095/a66df7ea-1205-11e6-8024-6415dcc2f598.png)

**Comment by grundic** [comment]
@camilocot fixed it in 68249d08183b22229f2b3d3cdd857eca72e02bd4

**Comment by andrew-boutin** [comment]
Confirmed attachment copying is working, thank you!
