### ISSUE TITLE
Bracket Errors {...}

### ISSUE THREAD

**Issue by andrew-boutin** [grundic/confluence-page-copier#5]
Putting {_any_text_} or {_any_number_} results in errors that are misleading.

Putting {random}, {bad}, {blah}, etc. in the destination title will fail the script and throw a key error.
Putting {1}, {2}, etc. in the destination title will fail the script and throw an index out of bounds error.
- Possibly add a check / throw an error to catch these occurrences?
- Possibly document to warn users not to use anything enclosed in brackets in the destination titles.
- Maybe you'll want to allow them to put brackets in the actual titles by using an escape character.

**Comment by grundic** [comment]
Nice catch.. Should escape input from user.

**Comment by andrew-boutin** [comment]
Couldn't find your email, wanted to say thanks for writing this script! Makes copying huge page trees much less of a pain.

**Comment by grundic** [comment]
Hey, @andrew-boutin! Thank you for your warm words, it's so great to know that my work helped someone :)

**Comment by grundic** [comment]
Fixed issue, but have not much time testing it.
If something goes wrong -- open a new ticket.

And sorry for waiting so long :|
