### ISSUE TITLE
Installation: "future" module is missing

### ISSUE THREAD

**Issue by rfominych** [grundic/confluence-page-copier#7]
after standard install using "pip install -r requirements.txt" command, trying to run application using Python 2 I got error:

Traceback (most recent call last):
  File "copier.py", line 11, in <module>
    from PythonConfluenceAPI import ConfluenceAPI
  File "c:\python27\lib\site-packages\PythonConfluenceAPI__init__.py", line 6, in <module>
    from future import standard_library
ImportError: No module named future

so then I run command:
"pip install future"

and application started working

so probably installation of "future" is missing

**Comment by grundic** [comment]
Hm.. I can't find it in my local working copy:

```
grep "future" . -Rl
```

Also, there is no **init**.py yet. Are you sure it's not a local problem?

**Comment by rfominych** [comment]
looks like error was thrown by PythonConfluenceAPI

so maybe it's out of scope here

**Comment by grundic** [comment]
[Indeed](https://github.com/pushrodtechnology/PythonConfluenceAPI/blob/master/PythonConfluenceAPI/__init__.py), looks like originally it came from `PythonConfluenceAPI`
