### ISSUE TITLE
Log command before downloading file: fails to output file name if it cannot be successfully formatted

### ISSUE THREAD

**Issue by rfominych** [grundic/confluence-page-copier#9]
line
self.log.debug("Downloading '{name}' attachment".format(name=attachment['title']))

had output:
File "copier.py", line 320, in _copy_attachments
    self.log.debug("Downloading '{name}' attachment".format(name=attachment['title']))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 49-51: ordinal not in range(128)

when:
filename contained BOM at the end of filename, that is EF BB BF (in hex), so "format" command was not able to format, and failed without telling what was that bad attachment/filename

for myself, I changed it to the following code and it worked
                #self.log.debug("Downloading '{name}' attachment".format(name=attachment['title']))
                self.log.debug("Downloading attachment:".format(name=attachment['title']))
                self.log.debug(attachment['title'])

![bom](https://cloud.githubusercontent.com/assets/14583611/16201506/42766a6c-3701-11e6-9ae8-21c8c4624932.png)

[file2.txt](https://github.com/grundic/confluence-page-copier/files/323827/file2.txt)

**Comment by grundic** [comment]
Fixed, can you verify, please?

**Comment by rfominych** [comment]
confirm, now filename is printed

INFO:confl-copier:Copying 1 attachment(s)
DEBUG:confl-copier:Downloading 'somefilename─Å┼Ñ┼╝.png' attachment
DEBUG:confl-copier:Creating new attachment 'somefilename─Å┼Ñ┼╝.png'
DEBUG:confl-copier:Removing temp directory 'c:\users\roman\appdata\local\temp\tmp2czejz'
Traceback (most recent call last):
  File "copier.py", line 471, in <module>
    recursion_limit=args.recursion_limit
  File "copier.py", line 117, in copy
    self._copy_attachments(source, page_copy_id)
  File "copier.py", line 347, in _copy_attachments
    shutil.rmtree(temp_dir)
  File "c:\python27\lib\shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "c:\python27\lib\shutil.py", line 250, in rmtree
    os.remove(fullname)
WindowsError: [Error 2] The system cannot find the file specified: 'c:\users\roman\appdata\local\temp\tmp2czejz\somefilenamedtz.png'
